language: python

python:
    - 3.6
    - 3.7

install:
    - pip install -r requirements.txt

script:
    - pylint department-app/service/rest_db_operations.py
    - pylint department-app/dbmodels.py
    - pylint department-app/app.py
    - python -m unittest discover

after_success:
    - coveralls

