language: python

python:
    - 3.5
    - 3.6
    - 3.7

install:
    - pip install -r requirements/dev.txt

script:
    - python -m unittest discover
    - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
    - coveralls

